pull_request_rules:
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - "status-success=ci/circleci: build"
    actions:
      merge:
        method: merge